[package]
name = "docdiff"
version = "0.1.0"
edition = "2024"
authors = ["Edmo Lima <soedmolima@gmail.com>"]
description = "A CLI tool for comparing two files using document distance algorithms."

[dependencies]
clap = { version = "4.5", features = ["derive"] }
anyhow = "1.0"
indicatif = "0.18"
