name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --all --verbose
      - name: Lint
        run: cargo clippy --all -- -D warnings
      - name: Check formatting
        run: cargo fmt --all -- --check
